### ISSUE TITLE
Scrolling on thimblecss.com/docs doesn't work in Microsoft Edge

### ISSUE THREAD

**Issue by aggieben** [agileleague/thimblecss#1]

**Comment by noltedesign** [comment]
Shoot, I'll look into this. I did remove some legacy Flexbox calls awhile ago.

**Comment by christianpiper** [comment]
Same with FF 59.0 (64-bit)

**Comment by lighth7015** [comment]
You're missing a `height: 95vh` on #docs-content, that will fix it.

**Comment by noltedesign** [comment]
Sorry about that, was for an old version, finally updated docs and simplified the whole page.
