### ISSUE TITLE
Is there current documentation for this project?

### ISSUE THREAD

**Issue by ckingbailey** [agileleague/thimblecss#3]
The top of the [docs](http://thimblecss.com/docs) has a note

> Note: this is for a legacy version of ThimbleCSS

but no link to documentation for the current version. There is a link to the [living style guide](http://thimblecss.com/style-guide), but all I see there is a definition of _icon_, and details of typography and colors. Notably absent is any mention of the grid or breakpoints.

I do see from inspecting the compiled css that the grid classes have changed, and there are small/medium/large breakpoint classes that are not mentioned in the legacy docs.

I really like ThimbleCSS for its small size and un-opinionated simplicity compared to something like Bulma, Bourbon, or Bootstrap, but the lack of documentation for v2 is almost a deal-breaker for me right now.

Is there documentation for v2 that I have simply failed to find a link to? If not, is documentation in the works? From `git blame` of the README, it looks like v2 was released 11 months ago.

**Comment by piotao** [comment]
Having such a poor documentation is a real bummer. I like the css and sass, but it will be nice to provide a complete and concise documentation which is at least NO MISLEADING.

Now, I had to read source code of SASS to understood that instead of column I should put vertical, and so on. Shame!

**Comment by noltedesign** [comment]
Sorry all, I've recently taken the time to update a few things and document the whole project, as I'm still working with and tweaking it. New simplified docs can be found here: https://thimblecss.com/

Since I'm using this in a larger development setting now, documentation will stay fresh and maintained.
